### ISSUE TITLE
error : when using both blur and mask component.

### ISSUE THREAD

**Issue by jhyoo2** [wheatup/cocos-creator-blur-mask#1]
Hello. I'm the indie game developer using Cocos Creator.

First. I want to say thank you for making this terrific source. I think it is very useful.

but unfortunately I found some error while quoting this source code to my project.

Error is when I using this blur effect, if there is mask component in the scene object(just one will be enough) blur effect make whole screen white.

I don't know how to fix it but I think you could know about it.

I tested this with cocos-creator v2.1.1 with window environment.

and if I deactive the mask component it works very smoothly :)

**Comment by wheatup** [comment]
Thanks for the feedback and yes I've noticed this issue as well.

Seems the `Blur` layer can't interpret the node which has `Mask` component correctly and renders itself and everything beneath it as pure white. I tried to upgrade the engine to version `2.1.2 rc3` but still doesn't work.

Although you can bypass this behavior by putting the node that has `Mask` into the `ignored list`, but the downside is the mask won't render that node at all.

It might be some glitch that comes with the engine itself. To solve this issue I have to dig deep into the source code or just report this issue to the engine dev team.

But I'll try what I can do about it first :/
