### ISSUE TITLE
提醒一下作者，下載下來後，發現疑似有兩個地方錯了。

### ISSUE THREAD

**Issue by LoopAllan** [wheatup/cocos-creator-blur-mask#5]
## 1. Shader 內的 function 順序錯誤。
![image](https://user-images.githubusercontent.com/41807202/65400602-bda5da80-ddf5-11e9-81c5-53642e75b869.png)
### 檔案 Blur.effect 內 (先宣告 rand() ，在宣告 blur())：
`float rand(vec2 co) {...}` <-- 這兩行順序應該是要這樣
`vec4 blur(vec2 uv){...}`

## 2. Shader 內的 blur() function 中值給錯了
￼
![1569210203280](https://user-images.githubusercontent.com/41807202/65403683-732d5980-de07-11e9-906e-0f6aaf8dc642.jpg)

**Comment by wheatup** [comment]
感谢反馈！已按照说明进行修复，但由于环境关系尚未进行测试。
